# -*- coding: utf-8 -*-
"""
pylix_class.py

Dataclass definitions for the pylix Bloch-wave simulation and refinement code.

Class hierarchy and responsibilities
-------------------------------------
Crystal  (xtal)
    Everything derived purely from the CIF unit cell: lattice parameters,
    space-group symmetry operations, and reference-frame transformations.
    Owns the symmetry_matrix / symmetry_vector arrays used in the gradient
    calculation (one rotation matrix and one translation vector per symop).

Basis  (basis)
    The asymmetric unit: the minimal set of atoms needed to generate the
    full unit cell when the symmetry operations in xtal are applied.
    Owns scattering-factor parameters (kappa, pv, f_g), occupancies, and
    anisotropic displacement parameters in the CIF/fractional frame.

Cell  (cell)
    The full unit cell: all atoms generated by applying xtal's symmetry
    operations to basis.  Owns fractional coordinates, Cartesian
    coordinates (in the microscope reference frame), anisotropic
    displacement parameters rotated into the microscope frame, and — for
    the analytical gradient — the two index arrays that record which basis
    atom and which symmetry operation generated each cell atom:
        basis_atom_index[k]  →  index into basis (0…basis.n_atoms−1)
        symop_index[k]       →  index into xtal.symmetry_matrix

HKL  (hkl)
    Miller indices read from felix.hkl (the output reflections requested by
    the user).  Distinct from the full beam pool built in Bloch.

Bloch  (bloch)
    Everything derived from the beam-pool construction and the pixel-by-pixel
    deviation-parameter calculation: g-vectors, the Ug matrix, deviation
    parameters, wave vectors, and the hkl_indices array (integer Miller
    indices for each beam in the pool, shape (n_hkl, 3)), which is needed
    by build_atom_ug_grad to form the h_diff differences.

RunControl  (rc)
    All parameters read from felix.inp, refinement state, and the
    atom_refine_vec array (shape (n_variables, 3)) that records the allowed
    fractional-coordinate movement direction for each coordinate refinement
    variable — set by atom_move / preferred_basis in pylix.py.

CBED  (cbed)
    Simulation outputs and their comparison with experiment:
        lacbed_sim   [n_thickness, imgX, imgY, n_out]   — simulated intensities
        lacbed_expt  [imgX, imgY, n_out]                — experimental patterns
        lacbed_diff  [n_thickness, imgX, imgY, n_out]   — sim − expt
        lacbed_sig   [n_variables, imgX, imgY, n_out]   — sensitivity images dI/dp
        lacbed_mask  [n_variables, imgX, imgY, n_out]   — thresholded sensitivity
        lacbed_grad  [n_grad_vars, n_thickness, imgX, imgY, n_out]
                                                        — analytical gradient dI/dp
                     n_grad_vars = number of coordinate refinement variables
                     (indexed by position in grad_var_indices, not by var_idx)
"""
import numpy as np
from numpy.typing import NDArray
from dataclasses import dataclass


# ----------------------------------------------------------------------------
# variables in felix.inp
@dataclass
class RunControl:
    """
    All parameters from felix.inp plus refinement state.

    Key gradient-related attributes
    --------------------------------
    atom_refine_flag : ndarray (n_variables,) int
        Index of the basis atom being refined for each variable.
        −1 for non-atomic variables.

    atom_refine_vec  : ndarray (n_variables, 3) float
        Fractional-coordinate direction in which basis atom
        atom_refine_flag[i] is allowed to move.  Set by atom_move /
        preferred_basis in pylix.py.  Used by build_atom_ug_grad as v.

    refined_variable_type : ndarray (n_variables,) int
        Variable type code.  Coordinate variables have type 20.

    All other attributes are populated from felix.inp.
    """
    # control
    write_flag = None
    scatter_factor_method = None
    holz_flag = None
    absorption_method = None
    absorption_per = None
    Debye_model = None
    accelerating_voltage_kv = None
    convergence_angle = None

    # beam selection criteria:
    min_reflection_pool = None
    min_strong_beams = None
    min_weak_beams = None
    g_limit = None

    debug = None
    plot = None
    n_output_reflexions = None

    # sample:
    incident_beam_direction = None
    x_direction = None
    normal = None
    initial_thickness = None
    final_thickness = None
    delta_thickness = None
    debye_waller_constant = None

    # microscope
    convergence_angle = None
    accelerating_voltage_kv = None
    acceptance_angle = None

    # output
    image_radius = None
    plot = None
    image_processing = None
    blur_radius = None
    print_flag = None
    debug = None

    # refinement:
    refine_mode = 'S'
    refine_method = None
    refinement_scale = None
    weighting_flag = None
    precision = None
    correlation_type = None
    atomic_sites = None
    no_of_ugs = None

    def update_from_dict(self, data):
        for key, value in data.items():
            if hasattr(self, key):
                setattr(self, key, value)

# ----------------------------------------------------------------------------
# run control variables derived from felix.inp

    thickness: NDArray[np.floating] | None = None  # ndarray of thickness values (Å)
    n_thickness: int = 0
    n_out: int = 0  # number of output reflections
    refined_variable: NDArray[np.floating] | None = None
    refined_variable_type: NDArray[np.integer] | None = None
    refined_variable_sigma: NDArray[np.floating] | None = None
    refined_variable_scale: NDArray[np.floating] | None = None
    refined_variable_fom: NDArray[np.floating] | None = None
    lacbed_fit_sigma: NDArray[np.floating] | None = None
    atom_refine_flag: NDArray[np.integer] | None = None
    atom_refine_vec: NDArray[np.floating] | None = None
    atom_coord_vec: NDArray[np.floating] | None = None
    moves: NDArray[np.floating] | None = None
    n_variables: int = 0
    n_correlations: int = 0
    best_fit: float = 0.0
    last_fit: float = 0.0
    best_var: NDArray[np.floating] | None = None
    fit_log: NDArray[np.floating] | None = None
    param_log: NDArray[np.floating] | None = None
    df: float = 1.0
    fom: float = 1.0
    iter_count: int = 0
    plot: int = 0
    path = None

# ----------------------------------------------------------------------------
# variables used in the Bloch wave calculation
@dataclass
class Bloch:
    """
    Beam pool and pixel-level Bloch-wave quantities.

    Attributes
    ----------
    n_hkl            : int  — total number of beams in the pool
    n_out            : int  — number of output beams (subset of n_hkl)

    hkl_indices      : ndarray (n_hkl, 3) int
        Integer Miller indices for every beam in the pool, in the same order
        as the rows/columns of ug_matrix, s_g, etc.
        Used by build_atom_ug_grad to compute h_diff[m,n] = hkl[m] − hkl[n].

    hkl_output       : ndarray (n_out,) int
        Indices into hkl_indices for the requested output beams.

    g_pool           : ndarray (n_hkl, 3)  — g-vectors (1/Å, microscope frame)
    g_pool_mag       : ndarray (n_hkl,)    — |g| (1/Å)
    g_matrix         : ndarray (n_hkl, n_hkl, 3)  — g_m − g_n vectors
    g_dot_norm       : ndarray (n_hkl,)    — g · n̂ (surface normal component)

    ug_matrix        : ndarray (n_hkl, n_hkl) complex  — optical potential
    s_g              : ndarray (imgX, imgY, n_hkl)     — deviation parameters
    k_dot_n          : ndarray (imgX, imgY)             — k · n̂ per pixel
    tilted_k         : ndarray (imgX, imgY, 3)          — k-vector per pixel

    big_k_mag        : float  — |K| in crystal (Å⁻¹)
    big_k            : ndarray (3,)  — K-vector in microscope frame
    relativistic_correction : float  — Lorentz factor γ
    electron_velocity       : float  — v (m/s)
    """
    electron_velocity: float = 0.0
    relativistic_correction: float = 0.0
    big_k: NDArray[np.floating] | None = None
    big_k_mag: float = 0.0
    tilted_k: NDArray[np.floating] | None = None
    k_dot_n: NDArray[np.floating] | None = None
    k_dot_n_pix: NDArray[np.floating] | None = None
    n_hkl: int = 0
    n_out: int = 0
    hkl_indices: NDArray[np.integer] | None = None
    hkl_output: NDArray[np.integer] | None = None
    g_pool: NDArray[np.floating] | None = None
    g_pool_mag: NDArray[np.floating] | None = None
    g_matrix: NDArray[np.floating] | None = None
    uniq_gmag: NDArray[np.floating] | None = None
    ug_matrix: NDArray[np.floating] | None = None
    g_dot_norm: NDArray[np.floating] | None = None
    s_g: NDArray[np.floating] | None = None
    s_g_pix: NDArray[np.floating] | None = None
    wave_function: NDArray[np.complex128] | None = None
    strong_beam: NDArray[np.integer] | None = None
    gamma: NDArray[np.complex128] | None = None
    eigenvecs: NDArray[np.complex128] | None = None
    n_beams: int = 0
    strong_beam_indices: NDArray[np.integer] | None = None


# ----------------------------------------------------------------------------
# variables output
@dataclass
class Cbed:
    """
    Simulation outputs and experimental data.

    Array shapes
    ------------
    lacbed_sim   : (n_thickness, imgX, imgY, n_out)      simulated intensities
    lacbed_expt  : (imgX, imgY, n_out)                   experimental patterns
    lacbed_expt_raw : (imgX, imgY, n_out)                unmodified experiment
    lacbed_diff  : (n_thickness, imgX, imgY, n_out)      sim − expt (normalised)
    lacbed_ref   : (imgX, imgY, n_out)                   reference simulation
    lacbed_sig   : (n_variables, imgX, imgY, n_out)      sensitivity dI/dp
    lacbed_mask  : (n_variables, imgX, imgY, n_out)      thresholded sensitivity

    lacbed_grad  : (n_grad_vars, n_thickness, imgX, imgY, n_out)
        Analytical gradient dI/dp for each coordinate refinement variable,
        already projected onto the allowed movement direction v.
        n_grad_vars = len(grad_var_indices) as built in simulate().
        The mapping from axis-0 index to var_idx is given by
        grad_var_indices (stored in simulate's shared_data).

    lacbed_mask_i, lacbed_mask_j : used in correlation analysis (mode X).
    correlation_matrix           : (n_correlations, n_out).
    """
    # arrays of images
    lacbed_sim: NDArray[np.floating] | None = None  # simulation
    lacbed_expt_raw: NDArray[np.floating] | None = None  # experiment
    lacbed_expt: NDArray[np.floating] | None = None  # experiment, processed
    # lacbed_grad gives gradient images for atomic coordinates
    # shape [n_grad_vars, n_thickness, imgX, imgY, n_out]
    lacbed_grad: NDArray[np.floating] | None = None
    lacbed_diff: NDArray[np.floating] | None = None  # difference sim:expt
    lacbed_ref: NDArray[np.floating] | None = None  # reference used for sig
    lacbed_sig: NDArray[np.floating] | None = None  # signature 
    lacbed_mask: NDArray[np.floating] | None = None  # masks
    lacbed_mask_i: NDArray[np.floating] | None = None  # masks for i
    lacbed_mask_j: NDArray[np.floating] | None = None  # masks for j
    correlation_matrix: NDArray[np.floating] | None = None  # correlations 
    # figures of merit, one per image
    diff_max: NDArray[np.floating] | None = None  # max difference ()
    diff_mean: NDArray[np.floating] | None = None


# ----------------------------------------------------------------------------
# variables in felix.cif
@dataclass
class Cif:
    # basis:
    atom_site_b_iso_or_equiv = None
    atom_site_aniso_label = None
    atom_site_aniso_type_symbol = None
    atom_site_label = None
    atom_site_type_symbol = None
    atom_site_symmetry_multiplicity = None
    atom_site_fract_x = None
    atom_site_fract_y = None
    atom_site_fract_z = None
    atom_site_occupancy = None
    atom_site_u_iso_or_equiv = None
    atom_site_wyckoff_symbol = None
    atom_site_aniso_u_11 = None
    atom_site_aniso_u_22 = None
    atom_site_aniso_u_33 = None
    atom_site_aniso_u_12 = None
    atom_site_aniso_u_13 = None
    atom_site_aniso_u_23 = None
    atom_site_aniso_label = None
    atom_site_aniso_type_symbol = None
    atom_site_pv = None
    atom_site_kappa = None
    atom_type_symbol = None
    atom_type_oxidation_number = None

    # cell:
    cell_angle_alpha = None
    cell_angle_beta = None
    cell_angle_gamma = None
    cell_length_a = None
    cell_length_b = None
    cell_length_c = None
    cell_volume = None

    # chemical:
    chemical_formula_iupac = None
    chemical_formula_structural = None
    chemical_formula_sum = None

    #  symmetry:
    space_group_it_number = None
    space_group_name_h_m_alt = None
    space_group_symbol = None
    space_group_symop_id = None
    space_group_symop_operation_xyz = None
    symmetry_equiv_pos_as_xyz = None
    symmetry_space_group_name_h_m = None

    def update_from_dict(self, data):
        for key, value in data.items():
            if hasattr(self, key):
                setattr(self, key, value)


# ----------------------------------------------------------------------------
# classes derived from the .cif file
@dataclass
class Crystal:
    """
    Unit-cell geometry and space-group symmetry.

    Attributes set at construction
    --------------------------------
    (all populated by CIF parsing and px.reference_frames)

    cell_a, cell_b, cell_c      : float  — lattice parameters (Å)
    cell_alpha, cell_beta,
    cell_gamma                  : float  — lattice angles (radians)
    cell_volume                 : float  — unit-cell volume (Å³)
    mott                        : float  — Mott–Bethe prefactor
    chemical_formula            : str

    symmetry_matrix : ndarray, shape (n_symops, 3, 3)
        Rotation part of each symmetry operation (fractional coordinates).
        symmetry_matrix[i] is the 3×3 matrix R_i for operation i.
        Used by build_atom_ug_grad to rotate the movement vector v:
            R_i @ v  →  effective displacement direction for cell atom k.

    symmetry_vector : ndarray, shape (n_symops, 3)
        Translation part of each symmetry operation (fractional coordinates).
        symmetry_vector[i] is the translation t_i for operation i.

    norm_dir_m   : ndarray (3,)  — surface normal in microscope frame
    x_dir_m      : ndarray (3,)  — x-direction in microscope frame
    y_dir_m      : ndarray (3,)  — y-direction in microscope frame
    a_vec_m, b_vec_m, c_vec_m   : ndarray (3,)  — lattice vectors in
                                   microscope frame
    """
    space_group: str = ""
    chemical_formula: str = ""
    lattice_type: str = ""
    space_group_number: int = 0
    symmetry_matrix: NDArray[np.integer] | None = None
    symmetry_vector: NDArray[np.floating] | None = None
    cell_a: float = 0.0
    cell_b: float = 0.0
    cell_c: float = 0.0
    cell_alpha: float = 0.0
    cell_beta: float = 0.0
    cell_gamma: float = 0.0
    cell_volume: float = 0.0
    a_vec_m: NDArray[np.floating] | None = None
    b_vec_m: NDArray[np.floating] | None = None
    c_vec_m: NDArray[np.floating] | None = None
    ar_vec_m: NDArray[np.floating] | None = None
    br_vec_m: NDArray[np.floating] | None = None
    cr_vec_m: NDArray[np.floating] | None = None
    norm_dir_m: NDArray[np.floating] | None = None
    t_mat_o2m: NDArray[np.floating] | None = None
    t_mat_c2o: NDArray[np.floating] | None = None
    t_mat_cr2mr: NDArray[np.floating] | None = None
    # kappa model
    n_points: int = 12000
    r_max: float = 12.0  # max radius to calculate electron density, Angstroms
    bohr_radius: float = 0.529177210544  # Angstroms
    mott: float = 0.02393366096322682  # prefactor in Mott-Bethe formula


@dataclass
class Basis:
    """
    Asymmetric unit — atoms before symmetry expansion.

    Attributes
    ----------
    n_atoms          : int
    atom_label       : list of str
    atom_name        : list of str
    atomic_number    : ndarray (n_atoms,) int
    atom_position    : ndarray (n_atoms, 3)  fractional coords in CIF frame
    wyckoff          : list of str
    occupancy        : ndarray (n_atoms,)
    mult_occ         : ndarray (n_atoms,)  multiplicity for shared-site bookkeeping
    u_aniso          : ndarray (n_atoms, 3, 3)  ADPs in CIF frame
    kappa            : ndarray (n_atoms,)
    pv               : ndarray (n_atoms,)
    f_g              : ndarray — scattering factors on the g-grid
    core, valence    : ndarray — RHF radial densities (kappa method)
    """
    n_atoms: int = 0
    atom_label: list | None = None
    atom_name: list | None = None
    oxno: NDArray[np.integer] | None = None
    atomic_number: NDArray[np.integer] | None = None
    wyckoff: list | None = None
    atom_position: NDArray[np.floating] | None = None
    occupancy: NDArray[np.floating] | None = None
    mult_occ: NDArray[np.integer] | None = None
    u_aniso: NDArray[np.floating] | None = None
    u_iso: NDArray[np.floating] | None = None
    B_iso: NDArray[np.floating] | None = None
    atom_delta: NDArray[np.floating] | None = None
    f_g: NDArray[np.complex128] | None = None
    f_g_prime: NDArray[np.complex128] | None = None
    # kappa model
    kappa: NDArray[np.floating] | None = None
    core: NDArray[np.floating] | None = None
    valence: NDArray[np.floating] | None = None
    pc: NDArray[np.floating] | None = None
    pv: NDArray[np.floating] | None = None
    n_electrons: NDArray[np.floating] | None = None


@dataclass
class Cell:
    """
    Full unit cell — all atoms after symmetry expansion.

    The symmetry expansion is performed by px.unique_atom_positions, which
    applies every operation in xtal.symmetry_matrix / symmetry_vector to
    each basis atom.  Two index arrays record the provenance of each cell
    atom:

    basis_atom_index : ndarray (n_atoms,) int
        basis_atom_index[k] = index of the basis atom (0…basis.n_atoms−1)
        that generated cell atom k.  Used in build_atom_ug_grad to select
        which cell atoms contribute to the gradient of a given refinement
        variable.

    symop_index : ndarray (n_atoms,) int
        symop_index[k] = index of the symmetry operation (row of
        xtal.symmetry_matrix) that generated cell atom k.  Used in
        build_atom_ug_grad to look up the rotation matrix R_k.

    All other attributes
    --------------------
    n_atoms          : int
    atom_label       : list of str
    atom_name        : list of str
    atomic_number    : ndarray (n_atoms,) int
    atom_position    : ndarray (n_atoms, 3)  fractional coords (CIF frame)
    atom_coordinate  : ndarray (n_atoms, 3)  Cartesian (microscope frame, Å)
    occupancy        : ndarray (n_atoms,)
    u_aniso          : ndarray (n_atoms, 3, 3)  ADPs (CIF frame)
    u_aniso_m        : ndarray (n_atoms, 3, 3)  ADPs (microscope frame)
    f_g              : ndarray (n_atoms, n_hkl, n_hkl) complex
                       scattering factors on the g-difference grid,
                       populated by px.Fg_matrix
    """
    n_atoms: int = 0
    atom_label: list | None = None
    atom_name: list | None = None
    oxno: NDArray[np.integer] | None = None
    atomic_number: NDArray[np.integer] | None = None
    wyckoff: list | None = None
    atom_position: NDArray[np.floating] | None = None  # in cell
    atom_coordinate: NDArray[np.floating] | None = None  # in microscope frame
    occupancy: NDArray[np.floating] | None = None
    mult_occ: NDArray[np.integer] | None = None
    u_aniso: NDArray[np.floating] | None = None  # in cell
    u_aniso_m: NDArray[np.floating] | None = None  # in microscope frame
    u_iso: NDArray[np.floating] | None = None
    B_iso: NDArray[np.floating] | None = None
    # basis_atom_index[k] = which basis atom generated cell atom k
    basis_atom_index: NDArray[np.integer] | None = None
    # symop_index[k] = which symmetry operation was applied
    symop_index:      NDArray[np.integer] | None = None
    atom_delta: NDArray[np.floating] | None = None
    f_g: NDArray[np.complex128] | None = None
    # kappa model
    kappa: NDArray[np.floating] | None = None
    core: NDArray[np.floating] | None = None
    valence: NDArray[np.floating] | None = None
    pc: NDArray[np.floating] | None = None
    pv: NDArray[np.floating] | None = None
    mean_sq_r2: NDArray[np.floating] | None = None


# -----------------------------------------------
@dataclass
class Hkl:  # hkl file
    """
    Requested output reflections (from felix.hkl).

    Attributes
    ----------
    hkl        : ndarray (n_out, 3) int   — Miller indices of output beams
    n_hkl      : int
    """
    input_hkls: NDArray[np.integer] | None = None
    i_obs: NDArray[np.floating] | None = None
    sigma_obs: NDArray[np.floating] | None = None
